### ISSUE TITLE
4k settings

### ISSUE THREAD

**Issue by wanwe** [lumpi2k/m93p-tiny-hackintosh#1]
hi Hannes,

I'm have exactly same hardware as you. may I know how you get 4k working?
I'm using your repo, but only getting 2k with my dell 4k monitor via DP. did you change bios settings for  Graphics DVMT ? 
appreciate your help !

Thanks,
Wei

**Comment by lumpi2k** [comment]
Hi Wei,

4K(60) is indeed an issue I'm still working on. I fiddled around with the device IDs in config.plist (https://github.com/lumpi2k/m93p-tiny-hackintosh/blob/1b235a675ed9af4e6771d05e2e53281503b59218/EFI/OC/config.plist#L196), but so far I only found two possible outcomes: 4k30 without proper graphics acceleration (which is slow) and 1080p, which works flawlessly. The HD4600 is perfectly capable of 4k60 in Windows, so I've not yet given up.

Here's a list of the device IDs I used with their respective results:
![image](https://user-images.githubusercontent.com/32732790/89010548-1942cd80-d30f-11ea-8737-af5b673df468.png)

At the moment I'm using a custom resolution which is above 1080 and fully accelerated, but blurry since it's not quite 4k. My hope is a future fix for whatevergreen.

**Comment by wanwe** [comment]
got it..I was hoping 4k30 could work, looks like need more research :) please do share the good news if you find it out !
thanks for sharing the EFI, I'm able to get everything working !

**Comment by wanwe** [comment]
@lumpi2k 
just to share I found [this](https://www.reddit.com/r/hackintosh/comments/h0z4yf/troubleshooting_4k_on_hd_4600_igpu_opencore/) while googling this issue
the "Patching 4k" worked ! the font looks a bit strange (not very clear).. maybe you can try and see how to improve :)

**Comment by wanwe** [comment]
@lumpi2k 
remove patch and try these device properties
framebuffer-stolenmem -> data 00000006
framebuffer-fbmem -> data 00000003

<img width="537" alt="Screenshot 2020-08-01 at 5 16 49 AM" src="https://user-images.githubusercontent.com/14243105/89078079-3aaac480-d3b6-11ea-8fad-3c9f4883d926.png">

<img width="896" alt="Screenshot 2020-08-01 at 5 19 05 AM" src="https://user-images.githubusercontent.com/14243105/89078340-d50b0800-d3b6-11ea-80da-382bb4988350.png">

**Comment by lumpi2k** [comment]
Ha, works for me too! I get some weird glitches in Edge (chromium) but safari seems to work fine. I'll incorporate the patch into the config.plist of the repo

**Comment by wanwe** [comment]
I didn't test Edge, not sure what's the issue, another possible property to tweak is framebuffer-cursormem, I saw some user mentioned it, maybe you can give it try
